# Generated by Django 4.2.6 on 2025-02-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0004_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("", "----"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
