# Generated by Django 4.2.6 on 2025-02-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0005_alter_position_name_alter_task_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="taskmanager.position"
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workers",
                to="taskmanager.team",
            ),
        ),
    ]
